# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dateparser.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='dateparser.proto',
  package='dateParser',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x64\x61teparser.proto\x12\ndateParser\x1a\x1fgoogle/protobuf/timestamp.proto\"\'\n\x10ParseDateRequest\x12\x13\n\x0bNaturalDate\x18\x01 \x01(\t\"^\n\x0eParseDateReply\x12.\n\nParsedDate\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0e\n\x06Offset\x18\x02 \x01(\x02\x12\x0c\n\x04\x44\x61te\x18\x03 \x01(\t2U\n\nDateParser\x12G\n\tParseDate\x12\x1c.dateParser.ParseDateRequest\x1a\x1a.dateParser.ParseDateReply\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_PARSEDATEREQUEST = _descriptor.Descriptor(
  name='ParseDateRequest',
  full_name='dateParser.ParseDateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='NaturalDate', full_name='dateParser.ParseDateRequest.NaturalDate', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=104,
)


_PARSEDATEREPLY = _descriptor.Descriptor(
  name='ParseDateReply',
  full_name='dateParser.ParseDateReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ParsedDate', full_name='dateParser.ParseDateReply.ParsedDate', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Offset', full_name='dateParser.ParseDateReply.Offset', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Date', full_name='dateParser.ParseDateReply.Date', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=200,
)

_PARSEDATEREPLY.fields_by_name['ParsedDate'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['ParseDateRequest'] = _PARSEDATEREQUEST
DESCRIPTOR.message_types_by_name['ParseDateReply'] = _PARSEDATEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ParseDateRequest = _reflection.GeneratedProtocolMessageType('ParseDateRequest', (_message.Message,), {
  'DESCRIPTOR' : _PARSEDATEREQUEST,
  '__module__' : 'dateparser_pb2'
  # @@protoc_insertion_point(class_scope:dateParser.ParseDateRequest)
  })
_sym_db.RegisterMessage(ParseDateRequest)

ParseDateReply = _reflection.GeneratedProtocolMessageType('ParseDateReply', (_message.Message,), {
  'DESCRIPTOR' : _PARSEDATEREPLY,
  '__module__' : 'dateparser_pb2'
  # @@protoc_insertion_point(class_scope:dateParser.ParseDateReply)
  })
_sym_db.RegisterMessage(ParseDateReply)



_DATEPARSER = _descriptor.ServiceDescriptor(
  name='DateParser',
  full_name='dateParser.DateParser',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=202,
  serialized_end=287,
  methods=[
  _descriptor.MethodDescriptor(
    name='ParseDate',
    full_name='dateParser.DateParser.ParseDate',
    index=0,
    containing_service=None,
    input_type=_PARSEDATEREQUEST,
    output_type=_PARSEDATEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATEPARSER)

DESCRIPTOR.services_by_name['DateParser'] = _DATEPARSER

# @@protoc_insertion_point(module_scope)
